name: 同步代码

on:
  push:
    branches: [ master,jdk17 ]
  pull_request:
    branches: [ master,jdk17 ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master #同步至 gitee
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:doctor-mesh/doctor-ui.git"
          destination-repo: "git@gitee.com:log4j/doctor-ui.git"
